package com.pulselive.demo;

import java.util.Arrays;
import java.util.List;

public class Main 
{
	public static void main(String[] args) 
	{		
		// match data for premier league 19-20
		List<Match> matches1920 = Arrays.asList(new Match("Liverpool", "Norwich", 4, 1),
				new Match("West Ham", "Man City", 0, 5), new Match("Bournemouth", "Sheffield United", 1, 1),
				new Match("Burnley", "Southampton", 3, 0), new Match("Crystal Palace", "Everton", 0, 0),
				new Match("Watford", "Brighton", 0, 3), new Match("Tottenham", "Aston Villa", 3, 1),
				new Match("Leicester", "Wolves", 0, 0), new Match("Newcastle", "Arsenal", 0, 1),
				new Match("Man United", "Chelsea", 4, 0), new Match("Arsenal", "Burnley", 2, 1),
				new Match("Aston Villa", "Bournemouth", 1, 2), new Match("Brighton", "West Ham", 1, 1),
				new Match("Everton", "Watford", 1, 0), new Match("Norwich", "Newcastle", 3, 1),
				new Match("Southampton", "Liverpool", 1, 2), new Match("Man City", "Tottenham", 2, 2),
				new Match("Sheffield United", "Crystal Palace", 1, 0), new Match("Chelsea", "Leicester", 1, 1),
				new Match("Wolves", "Man United", 1, 1), new Match("Aston Villa", "Everton", 2, 0),
				new Match("Norwich", "Chelsea", 2, 3), new Match("Brighton", "Southampton", 0, 2),
				new Match("Man United", "Crystal Palace", 1, 2), new Match("Sheffield United", "Leicester", 1, 2),
				new Match("Watford", "West Ham", 1, 3), new Match("Liverpool", "Arsenal", 3, 1),
				new Match("Bournemouth", "Man City", 1, 3), new Match("Tottenham", "Newcastle", 0, 1),
				new Match("Wolves", "Burnley", 1, 1), new Match("Southampton", "Man United", 1, 1),
				new Match("Chelsea", "Sheffield United", 2, 2), new Match("Crystal Palace", "Aston Villa", 1, 0),
				new Match("Leicester", "Bournemouth", 3, 1), new Match("Man City", "Brighton", 4, 0),
				new Match("Newcastle", "Watford", 1, 1), new Match("West Ham", "Norwich", 2, 0),
				new Match("Burnley", "Liverpool", 0, 3), new Match("Everton", "Wolves", 3, 2),
				new Match("Arsenal", "Tottenham", 2, 2), new Match("Liverpool", "Newcastle", 3, 1),
				new Match("Brighton", "Burnley", 1, 1), new Match("Man United", "Leicester", 1, 0),
				new Match("Sheffield United", "Southampton", 0, 1), new Match("Tottenham", "Crystal Palace", 4, 0),
				new Match("Wolves", "Chelsea", 2, 5), new Match("Norwich", "Man City", 3, 2),
				new Match("Bournemouth", "Everton", 3, 1), new Match("Watford", "Arsenal", 2, 2),
				new Match("Aston Villa", "West Ham", 0, 0), new Match("Southampton", "Bournemouth", 1, 3),
				new Match("Leicester", "Tottenham", 2, 1), new Match("Burnley", "Norwich", 2, 0),
				new Match("Everton", "Sheffield United", 0, 2), new Match("Man City", "Watford", 8, 0),
				new Match("Newcastle", "Brighton", 0, 0), new Match("Crystal Palace", "Wolves", 1, 1),
				new Match("West Ham", "Man United", 2, 0), new Match("Arsenal", "Aston Villa", 3, 2),
				new Match("Chelsea", "Liverpool", 1, 2), new Match("Sheffield United", "Liverpool", 0, 1),
				new Match("Aston Villa", "Burnley", 2, 2), new Match("Bournemouth", "West Ham", 2, 2),
				new Match("Chelsea", "Brighton", 2, 0), new Match("Crystal Palace", "Norwich", 2, 0),
				new Match("Tottenham", "Southampton", 2, 1), new Match("Wolves", "Watford", 2, 0),
				new Match("Everton", "Man City", 1, 3), new Match("Leicester", "Newcastle", 5, 0),
				new Match("Man United", "Arsenal", 1, 1), new Match("Brighton", "Tottenham", 3, 0),
				new Match("Burnley", "Everton", 1, 0), new Match("Liverpool", "Leicester", 2, 1),
				new Match("Norwich", "Aston Villa", 1, 5), new Match("Watford", "Sheffield United", 0, 0),
				new Match("West Ham", "Crystal Palace", 1, 2), new Match("Arsenal", "Bournemouth", 1, 0),
				new Match("Man City", "Wolves", 0, 2), new Match("Southampton", "Chelsea", 1, 4),
				new Match("Newcastle", "Man United", 1, 0), new Match("Everton", "West Ham", 2, 0),
				new Match("Aston Villa", "Brighton", 2, 1), new Match("Bournemouth", "Norwich", 0, 0),
				new Match("Chelsea", "Newcastle", 1, 0), new Match("Leicester", "Burnley", 2, 1),
				new Match("Tottenham", "Watford", 1, 1), new Match("Wolves", "Southampton", 1, 1),
				new Match("Crystal Palace", "Man City", 0, 2), new Match("Man United", "Liverpool", 1, 1),
				new Match("Sheffield United", "Arsenal", 1, 0), new Match("Southampton", "Leicester", 0, 9),
				new Match("Man City", "Aston Villa", 3, 0), new Match("Brighton", "Everton", 3, 2),
				new Match("Watford", "Bournemouth", 0, 0), new Match("West Ham", "Sheffield United", 1, 1),
				new Match("Burnley", "Chelsea", 2, 4), new Match("Newcastle", "Wolves", 1, 1),
				new Match("Arsenal", "Crystal Palace", 2, 2), new Match("Liverpool", "Tottenham", 2, 1),
				new Match("Norwich", "Man United", 1, 3), new Match("Bournemouth", "Man United", 1, 0),
				new Match("Arsenal", "Wolves", 1, 1), new Match("Aston Villa", "Liverpool", 1, 2),
				new Match("Brighton", "Norwich", 2, 0), new Match("Man City", "Southampton", 2, 1),
				new Match("Sheffield United", "Burnley", 3, 0), new Match("West Ham", "Newcastle", 2, 3),
				new Match("Watford", "Chelsea", 1, 2), new Match("Crystal Palace", "Leicester", 0, 2),
				new Match("Everton", "Tottenham", 1, 1), new Match("Norwich", "Watford", 0, 2),
				new Match("Chelsea", "Crystal Palace", 2, 0), new Match("Burnley", "West Ham", 3, 0),
				new Match("Newcastle", "Bournemouth", 2, 1), new Match("Southampton", "Everton", 1, 2),
				new Match("Tottenham", "Sheffield United", 1, 1), new Match("Leicester", "Arsenal", 2, 0),
				new Match("Man United", "Brighton", 3, 1), new Match("Wolves", "Aston Villa", 2, 1),
				new Match("Liverpool", "Man City", 3, 1), new Match("West Ham", "Tottenham", 2, 3),
				new Match("Arsenal", "Southampton", 2, 2), new Match("Bournemouth", "Wolves", 1, 2),
				new Match("Brighton", "Leicester", 0, 2), new Match("Crystal Palace", "Liverpool", 1, 2),
				new Match("Everton", "Norwich", 0, 2), new Match("Watford", "Burnley", 0, 3),
				new Match("Man City", "Chelsea", 2, 1), new Match("Sheffield United", "Man United", 3, 3),
				new Match("Aston Villa", "Newcastle", 2, 0), new Match("Newcastle", "Man City", 2, 2),
				new Match("Burnley", "Crystal Palace", 0, 2), new Match("Chelsea", "West Ham", 0, 1),
				new Match("Liverpool", "Brighton", 2, 1), new Match("Tottenham", "Bournemouth", 3, 2),
				new Match("Southampton", "Watford", 2, 1), new Match("Norwich", "Arsenal", 2, 2),
				new Match("Wolves", "Sheffield United", 1, 1), new Match("Leicester", "Everton", 2, 1),
				new Match("Man United", "Aston Villa", 2, 2), new Match("Crystal Palace", "Bournemouth", 1, 0),
				new Match("Burnley", "Man City", 1, 4), new Match("Chelsea", "Aston Villa", 2, 1),
				new Match("Leicester", "Watford", 2, 0), new Match("Man United", "Tottenham", 2, 1),
				new Match("Southampton", "Norwich", 2, 1), new Match("Wolves", "West Ham", 2, 0),
				new Match("Liverpool", "Everton", 5, 2), new Match("Sheffield United", "Newcastle", 0, 2),
				new Match("Arsenal", "Brighton", 1, 2), new Match("Everton", "Chelsea", 3, 1),
				new Match("Bournemouth", "Liverpool", 0, 3), new Match("Tottenham", "Burnley", 5, 0),
				new Match("Watford", "Crystal Palace", 0, 0), new Match("Man City", "Man United", 1, 2),
				new Match("Aston Villa", "Leicester", 1, 4), new Match("Newcastle", "Southampton", 2, 1),
				new Match("Norwich", "Sheffield United", 1, 2), new Match("Brighton", "Wolves", 2, 2),
				new Match("West Ham", "Arsenal", 1, 3), new Match("Liverpool", "Watford", 2, 0),
				new Match("Burnley", "Newcastle", 1, 0), new Match("Chelsea", "Bournemouth", 0, 1),
				new Match("Leicester", "Norwich", 1, 1), new Match("Sheffield United", "Aston Villa", 2, 0),
				new Match("Southampton", "West Ham", 0, 1), new Match("Man United", "Everton", 1, 1),
				new Match("Wolves", "Tottenham", 1, 2), new Match("Arsenal", "Man City", 0, 3),
				new Match("Crystal Palace", "Brighton", 1, 1), new Match("Everton", "Arsenal", 0, 0),
				new Match("Aston Villa", "Southampton", 1, 3), new Match("Bournemouth", "Burnley", 0, 1),
				new Match("Brighton", "Sheffield United", 0, 1), new Match("Newcastle", "Crystal Palace", 1, 0),
				new Match("Norwich", "Wolves", 1, 2), new Match("Man City", "Leicester", 3, 1),
				new Match("Watford", "Man United", 2, 0), new Match("Tottenham", "Chelsea", 0, 2),
				new Match("Tottenham", "Brighton", 2, 1), new Match("Aston Villa", "Norwich", 1, 0),
				new Match("Bournemouth", "Arsenal", 1, 1), new Match("Chelsea", "Southampton", 0, 2),
				new Match("Crystal Palace", "West Ham", 2, 1), new Match("Everton", "Burnley", 1, 0),
				new Match("Sheffield United", "Watford", 1, 1), new Match("Man United", "Newcastle", 4, 1),
				new Match("Leicester", "Liverpool", 0, 4), new Match("Wolves", "Man City", 3, 2),
				new Match("Brighton", "Bournemouth", 2, 0), new Match("Newcastle", "Everton", 1, 2),
				new Match("Southampton", "Crystal Palace", 1, 1), new Match("Watford", "Aston Villa", 3, 0),
				new Match("Norwich", "Tottenham", 2, 2), new Match("West Ham", "Leicester", 1, 2),
				new Match("Burnley", "Man United", 0, 2), new Match("Arsenal", "Chelsea", 1, 2),
				new Match("Liverpool", "Wolves", 1, 0), new Match("Man City", "Sheffield United", 2, 0),
				new Match("Brighton", "Chelsea", 1, 1), new Match("Burnley", "Aston Villa", 1, 2),
				new Match("Newcastle", "Leicester", 0, 3), new Match("Southampton", "Tottenham", 1, 0),
				new Match("Watford", "Wolves", 2, 1), new Match("Man City", "Everton", 2, 1),
				new Match("Norwich", "Crystal Palace", 1, 1), new Match("West Ham", "Bournemouth", 4, 0),
				new Match("Arsenal", "Man United", 2, 0), new Match("Liverpool", "Sheffield United", 2, 0),
				new Match("Sheffield United", "West Ham", 1, 0), new Match("Crystal Palace", "Arsenal", 1, 1),
				new Match("Chelsea", "Burnley", 3, 0), new Match("Everton", "Brighton", 1, 0),
				new Match("Leicester", "Southampton", 1, 2), new Match("Man United", "Norwich", 4, 0),
				new Match("Wolves", "Newcastle", 1, 1), new Match("Tottenham", "Liverpool", 0, 1),
				new Match("Bournemouth", "Watford", 0, 3), new Match("Aston Villa", "Man City", 1, 6),
				new Match("Watford", "Tottenham", 0, 0), new Match("Arsenal", "Sheffield United", 1, 1),
				new Match("Brighton", "Aston Villa", 1, 1), new Match("Man City", "Crystal Palace", 2, 2),
				new Match("Norwich", "Bournemouth", 1, 0), new Match("Southampton", "Wolves", 2, 3),
				new Match("West Ham", "Everton", 1, 1), new Match("Newcastle", "Chelsea", 1, 0),
				new Match("Burnley", "Leicester", 2, 1), new Match("Liverpool", "Man United", 2, 0),
				new Match("Aston Villa", "Watford", 2, 1), new Match("Bournemouth", "Brighton", 3, 1),
				new Match("Crystal Palace", "Southampton", 0, 2), new Match("Everton", "Newcastle", 2, 2),
				new Match("Sheffield United", "Man City", 0, 1), new Match("Chelsea", "Arsenal", 2, 2),
				new Match("Leicester", "West Ham", 4, 1), new Match("Tottenham", "Norwich", 2, 1),
				new Match("Man United", "Burnley", 0, 2), new Match("Wolves", "Liverpool", 1, 2),
				new Match("West Ham", "Liverpool", 0, 2), new Match("Leicester", "Chelsea", 2, 2),
				new Match("Bournemouth", "Aston Villa", 2, 1), new Match("Crystal Palace", "Sheffield United", 0, 1),
				new Match("Liverpool", "Southampton", 4, 0), new Match("Newcastle", "Norwich", 0, 0),
				new Match("Watford", "Everton", 2, 3), new Match("West Ham", "Brighton", 3, 3),
				new Match("Man United", "Wolves", 0, 0), new Match("Burnley", "Arsenal", 0, 0),
				new Match("Tottenham", "Man City", 2, 0), new Match("Everton", "Crystal Palace", 3, 1),
				new Match("Brighton", "Watford", 1, 1), new Match("Sheffield United", "Bournemouth", 2, 1),
				new Match("Wolves", "Leicester", 0, 0), new Match("Southampton", "Burnley", 1, 2),
				new Match("Norwich", "Liverpool", 0, 1), new Match("Aston Villa", "Tottenham", 2, 3),
				new Match("Arsenal", "Newcastle", 4, 0), new Match("Chelsea", "Man United", 0, 2),
				new Match("Man City", "West Ham", 2, 0), new Match("Chelsea", "Tottenham", 2, 1),
				new Match("Burnley", "Bournemouth", 3, 0), new Match("Crystal Palace", "Newcastle", 1, 0),
				new Match("Sheffield United", "Brighton", 1, 1), new Match("Southampton", "Aston Villa", 2, 0),
				new Match("Leicester", "Man City", 0, 1), new Match("Man United", "Watford", 3, 0),
				new Match("Wolves", "Norwich", 3, 0), new Match("Arsenal", "Everton", 3, 2),
				new Match("Liverpool", "West Ham", 3, 2), new Match("Norwich", "Leicester", 1, 0),
				new Match("Brighton", "Crystal Palace", 0, 1), new Match("Bournemouth", "Chelsea", 2, 2),
				new Match("Newcastle", "Burnley", 0, 0), new Match("West Ham", "Southampton", 3, 1),
				new Match("Watford", "Liverpool", 3, 0), new Match("Everton", "Man United", 1, 1),
				new Match("Tottenham", "Wolves", 2, 3), new Match("Liverpool", "Bournemouth", 2, 1),
				new Match("Arsenal", "West Ham", 1, 0), new Match("Crystal Palace", "Watford", 1, 0),
				new Match("Sheffield United", "Norwich", 1, 0), new Match("Southampton", "Newcastle", 0, 1),
				new Match("Wolves", "Brighton", 0, 0), new Match("Burnley", "Tottenham", 1, 1),
				new Match("Chelsea", "Everton", 4, 0), new Match("Man United", "Man City", 2, 0),
				new Match("Leicester", "Aston Villa", 4, 0), new Match("Aston Villa", "Sheffield United", 0, 0),
				new Match("Man City", "Arsenal", 3, 0), new Match("Norwich", "Southampton", 0, 3),
				new Match("Tottenham", "Man United", 1, 1), new Match("Watford", "Leicester", 1, 1),
				new Match("Brighton", "Arsenal", 2, 1), new Match("West Ham", "Wolves", 0, 2),
				new Match("Bournemouth", "Crystal Palace", 0, 2), new Match("Newcastle", "Sheffield United", 3, 0),
				new Match("Aston Villa", "Chelsea", 1, 2), new Match("Everton", "Liverpool", 0, 0),
				new Match("Man City", "Burnley", 5, 0), new Match("Leicester", "Brighton", 0, 0),
				new Match("Tottenham", "West Ham", 2, 0), new Match("Man United", "Sheffield United", 3, 0),
				new Match("Newcastle", "Aston Villa", 1, 1), new Match("Norwich", "Everton", 0, 1),
				new Match("Wolves", "Bournemouth", 1, 0), new Match("Liverpool", "Crystal Palace", 4, 0),
				new Match("Burnley", "Watford", 1, 0), new Match("Southampton", "Arsenal", 0, 2),
				new Match("Chelsea", "Man City", 2, 1), new Match("Aston Villa", "Wolves", 0, 1),
				new Match("Watford", "Southampton", 1, 3), new Match("Crystal Palace", "Burnley", 0, 1),
				new Match("Brighton", "Man United", 0, 3), new Match("Arsenal", "Norwich", 4, 0),
				new Match("Bournemouth", "Newcastle", 1, 4), new Match("Everton", "Leicester", 2, 1),
				new Match("West Ham", "Chelsea", 3, 2), new Match("Sheffield United", "Tottenham", 3, 1),
				new Match("Man City", "Liverpool", 4, 0), new Match("Norwich", "Brighton", 0, 1),
				new Match("Leicester", "Crystal Palace", 3, 0), new Match("Man United", "Bournemouth", 5, 2),
				new Match("Wolves", "Arsenal", 0, 2), new Match("Chelsea", "Watford", 3, 0),
				new Match("Burnley", "Sheffield United", 1, 1), new Match("Newcastle", "West Ham", 2, 2),
				new Match("Liverpool", "Aston Villa", 2, 0), new Match("Southampton", "Man City", 1, 0),
				new Match("Tottenham", "Everton", 1, 0), new Match("Crystal Palace", "Chelsea", 2, 3),
				new Match("Watford", "Norwich", 2, 1), new Match("Arsenal", "Leicester", 1, 1),
				new Match("Man City", "Newcastle", 5, 0), new Match("Sheffield United", "Wolves", 1, 0),
				new Match("West Ham", "Burnley", 0, 1), new Match("Brighton", "Liverpool", 1, 3),
				new Match("Bournemouth", "Tottenham", 0, 0), new Match("Everton", "Southampton", 1, 1),
				new Match("Aston Villa", "Man United", 0, 3), new Match("Norwich", "West Ham", 0, 4),
				new Match("Watford", "Newcastle", 2, 1), new Match("Liverpool", "Burnley", 1, 1),
				new Match("Sheffield United", "Chelsea", 3, 0), new Match("Brighton", "Man City", 0, 5),
				new Match("Wolves", "Everton", 3, 0), new Match("Aston Villa", "Crystal Palace", 2, 0),
				new Match("Tottenham", "Arsenal", 2, 1), new Match("Bournemouth", "Leicester", 4, 1),
				new Match("Man United", "Southampton", 2, 2), new Match("Chelsea", "Norwich", 1, 0),
				new Match("Burnley", "Wolves", 1, 1), new Match("Man City", "Bournemouth", 2, 1),
				new Match("Newcastle", "Tottenham", 1, 3), new Match("Arsenal", "Liverpool", 2, 1),
				new Match("Everton", "Aston Villa", 1, 1), new Match("Leicester", "Sheffield United", 2, 0),
				new Match("Crystal Palace", "Man United", 0, 2), new Match("Southampton", "Brighton", 1, 1),
				new Match("West Ham", "Watford", 3, 1), new Match("Norwich", "Burnley", 0, 2),
				new Match("Bournemouth", "Southampton", 0, 2), new Match("Tottenham", "Leicester", 3, 0),
				new Match("Brighton", "Newcastle", 0, 0), new Match("Sheffield United", "Everton", 0, 1),
				new Match("Wolves", "Crystal Palace", 2, 0), new Match("Watford", "Man City", 0, 4),
				new Match("Aston Villa", "Arsenal", 1, 0), new Match("Man United", "West Ham", 1, 1),
				new Match("Liverpool", "Chelsea", 5, 3), new Match("Arsenal", "Watford", 3, 2),
				new Match("Burnley", "Brighton", 1, 2), new Match("Chelsea", "Wolves", 2, 0),
				new Match("Crystal Palace", "Tottenham", 1, 1), new Match("Everton", "Bournemouth", 1, 3),
				new Match("Leicester", "Man United", 0, 2), new Match("Man City", "Norwich", 5, 0),
				new Match("Newcastle", "Liverpool", 1, 3), new Match("Southampton", "Sheffield United", 3, 1),
				new Match("West Ham", "Aston Villa", 1, 1));

		// match data for premier league 18-19
		List<Match> matches1819 = Arrays.asList(new Match("Man United", "Leicester", 2, 1),
				new Match("Bournemouth", "Cardiff", 2, 0), new Match("Fulham", "Crystal Palace", 0, 2),
				new Match("Huddersfield", "Chelsea", 0, 3), new Match("Newcastle", "Tottenham", 1, 2),
				new Match("Watford", "Brighton", 2, 0), new Match("Wolves", "Everton", 2, 2),
				new Match("Arsenal", "Man City", 0, 2), new Match("Liverpool", "West Ham", 4, 0),
				new Match("Southampton", "Burnley", 0, 0), new Match("Cardiff", "Newcastle", 0, 0),
				new Match("Chelsea", "Arsenal", 3, 2), new Match("Everton", "Southampton", 2, 1),
				new Match("Leicester", "Wolves", 2, 0), new Match("Tottenham", "Fulham", 3, 1),
				new Match("West Ham", "Bournemouth", 1, 2), new Match("Brighton", "Man United", 3, 2),
				new Match("Burnley", "Watford", 1, 3), new Match("Man City", "Huddersfield", 6, 1),
				new Match("Crystal Palace", "Liverpool", 0, 2), new Match("Arsenal", "West Ham", 3, 1),
				new Match("Bournemouth", "Everton", 2, 2), new Match("Huddersfield", "Cardiff", 0, 0),
				new Match("Liverpool", "Brighton", 1, 0), new Match("Southampton", "Leicester", 1, 2),
				new Match("Wolves", "Man City", 1, 1), new Match("Fulham", "Burnley", 4, 2),
				new Match("Newcastle", "Chelsea", 1, 2), new Match("Watford", "Crystal Palace", 2, 1),
				new Match("Man United", "Tottenham", 0, 3), new Match("Brighton", "Fulham", 2, 2),
				new Match("Chelsea", "Bournemouth", 2, 0), new Match("Crystal Palace", "Southampton", 0, 2),
				new Match("Everton", "Huddersfield", 1, 1), new Match("Leicester", "Liverpool", 1, 2),
				new Match("Man City", "Newcastle", 2, 1), new Match("West Ham", "Wolves", 0, 1),
				new Match("Burnley", "Man United", 0, 2), new Match("Cardiff", "Arsenal", 2, 3),
				new Match("Watford", "Tottenham", 2, 1), new Match("Bournemouth", "Leicester", 4, 2),
				new Match("Chelsea", "Cardiff", 4, 1), new Match("Huddersfield", "Crystal Palace", 0, 1),
				new Match("Man City", "Fulham", 3, 0), new Match("Newcastle", "Arsenal", 1, 2),
				new Match("Tottenham", "Liverpool", 1, 2), new Match("Watford", "Man United", 1, 2),
				new Match("Everton", "West Ham", 1, 3), new Match("Wolves", "Burnley", 1, 0),
				new Match("Southampton", "Brighton", 2, 2), new Match("Brighton", "Tottenham", 1, 2),
				new Match("Burnley", "Bournemouth", 4, 0), new Match("Cardiff", "Man City", 0, 5),
				new Match("Crystal Palace", "Newcastle", 0, 0), new Match("Fulham", "Watford", 1, 1),
				new Match("Leicester", "Huddersfield", 3, 1), new Match("Liverpool", "Southampton", 3, 0),
				new Match("Man United", "Wolves", 1, 1), new Match("Arsenal", "Everton", 2, 0),
				new Match("West Ham", "Chelsea", 0, 0), new Match("Arsenal", "Watford", 2, 0),
				new Match("Chelsea", "Liverpool", 1, 1), new Match("Everton", "Fulham", 3, 0),
				new Match("Huddersfield", "Tottenham", 0, 2), new Match("Man City", "Brighton", 2, 0),
				new Match("Newcastle", "Leicester", 0, 2), new Match("West Ham", "Man United", 3, 1),
				new Match("Wolves", "Southampton", 2, 0), new Match("Cardiff", "Burnley", 1, 2),
				new Match("Bournemouth", "Crystal Palace", 2, 1), new Match("Brighton", "West Ham", 1, 0),
				new Match("Burnley", "Huddersfield", 1, 1), new Match("Crystal Palace", "Wolves", 0, 1),
				new Match("Leicester", "Everton", 1, 2), new Match("Man United", "Newcastle", 3, 2),
				new Match("Tottenham", "Cardiff", 1, 0), new Match("Watford", "Bournemouth", 0, 4),
				new Match("Fulham", "Arsenal", 1, 5), new Match("Liverpool", "Man City", 0, 0),
				new Match("Southampton", "Chelsea", 0, 3), new Match("Bournemouth", "Southampton", 0, 0),
				new Match("Cardiff", "Fulham", 4, 2), new Match("Chelsea", "Man United", 2, 2),
				new Match("Huddersfield", "Liverpool", 0, 1), new Match("Man City", "Burnley", 5, 0),
				new Match("Newcastle", "Brighton", 0, 1), new Match("West Ham", "Tottenham", 0, 1),
				new Match("Wolves", "Watford", 0, 2), new Match("Everton", "Crystal Palace", 2, 0),
				new Match("Arsenal", "Leicester", 3, 1), new Match("Brighton", "Wolves", 1, 0),
				new Match("Fulham", "Bournemouth", 0, 3), new Match("Leicester", "West Ham", 1, 1),
				new Match("Liverpool", "Cardiff", 4, 1), new Match("Southampton", "Newcastle", 0, 0),
				new Match("Watford", "Huddersfield", 3, 0), new Match("Burnley", "Chelsea", 0, 4),
				new Match("Crystal Palace", "Arsenal", 2, 2), new Match("Man United", "Everton", 2, 1),
				new Match("Tottenham", "Man City", 0, 1), new Match("Arsenal", "Liverpool", 1, 1),
				new Match("Bournemouth", "Man United", 1, 2), new Match("Cardiff", "Leicester", 0, 1),
				new Match("Everton", "Brighton", 3, 1), new Match("Newcastle", "Watford", 1, 0),
				new Match("West Ham", "Burnley", 4, 2), new Match("Wolves", "Tottenham", 2, 3),
				new Match("Chelsea", "Crystal Palace", 3, 1), new Match("Man City", "Southampton", 6, 1),
				new Match("Huddersfield", "Fulham", 1, 0), new Match("Cardiff", "Brighton", 2, 1),
				new Match("Crystal Palace", "Tottenham", 0, 1), new Match("Huddersfield", "West Ham", 1, 1),
				new Match("Leicester", "Burnley", 0, 0), new Match("Newcastle", "Bournemouth", 2, 1),
				new Match("Southampton", "Watford", 1, 1), new Match("Arsenal", "Wolves", 1, 1),
				new Match("Chelsea", "Everton", 0, 0), new Match("Liverpool", "Fulham", 2, 0),
				new Match("Man City", "Man United", 3, 1), new Match("Brighton", "Leicester", 1, 1),
				new Match("Everton", "Cardiff", 1, 0), new Match("Fulham", "Southampton", 3, 2),
				new Match("Man United", "Crystal Palace", 0, 0), new Match("Tottenham", "Chelsea", 3, 1),
				new Match("Watford", "Liverpool", 0, 3), new Match("West Ham", "Man City", 0, 4),
				new Match("Bournemouth", "Arsenal", 1, 2), new Match("Wolves", "Huddersfield", 0, 2),
				new Match("Burnley", "Newcastle", 1, 2), new Match("Cardiff", "Wolves", 2, 1),
				new Match("Crystal Palace", "Burnley", 2, 0), new Match("Huddersfield", "Brighton", 1, 2),
				new Match("Leicester", "Watford", 2, 0), new Match("Man City", "Bournemouth", 3, 1),
				new Match("Newcastle", "West Ham", 0, 3), new Match("Southampton", "Man United", 2, 2),
				new Match("Arsenal", "Tottenham", 4, 2), new Match("Chelsea", "Fulham", 2, 0),
				new Match("Liverpool", "Everton", 1, 0), new Match("Bournemouth", "Huddersfield", 2, 1),
				new Match("Brighton", "Crystal Palace", 3, 1), new Match("Watford", "Man City", 1, 2),
				new Match("West Ham", "Cardiff", 3, 1), new Match("Burnley", "Liverpool", 1, 3),
				new Match("Everton", "Newcastle", 1, 1), new Match("Fulham", "Leicester", 1, 1),
				new Match("Man United", "Arsenal", 2, 2), new Match("Tottenham", "Southampton", 3, 1),
				new Match("Wolves", "Chelsea", 2, 1), new Match("Arsenal", "Huddersfield", 1, 0),
				new Match("Bournemouth", "Liverpool", 0, 4), new Match("Burnley", "Brighton", 1, 0),
				new Match("Cardiff", "Southampton", 1, 0), new Match("Chelsea", "Man City", 2, 0),
				new Match("Leicester", "Tottenham", 0, 2), new Match("Man United", "Fulham", 4, 1),
				new Match("West Ham", "Crystal Palace", 3, 2), new Match("Newcastle", "Wolves", 1, 2),
				new Match("Everton", "Watford", 2, 2), new Match("Crystal Palace", "Leicester", 1, 0),
				new Match("Fulham", "West Ham", 0, 2), new Match("Huddersfield", "Newcastle", 0, 1),
				new Match("Man City", "Everton", 3, 1), new Match("Tottenham", "Burnley", 1, 0),
				new Match("Watford", "Cardiff", 3, 2), new Match("Wolves", "Bournemouth", 2, 0),
				new Match("Brighton", "Chelsea", 1, 2), new Match("Liverpool", "Man United", 3, 1),
				new Match("Southampton", "Arsenal", 3, 2), new Match("Wolves", "Liverpool", 0, 2),
				new Match("Arsenal", "Burnley", 3, 1), new Match("Bournemouth", "Brighton", 2, 0),
				new Match("Cardiff", "Man United", 1, 5), new Match("Chelsea", "Leicester", 0, 1),
				new Match("Huddersfield", "Southampton", 1, 3), new Match("Man City", "Crystal Palace", 2, 3),
				new Match("Newcastle", "Fulham", 0, 0), new Match("West Ham", "Watford", 0, 2),
				new Match("Everton", "Tottenham", 2, 6), new Match("Brighton", "Arsenal", 1, 1),
				new Match("Burnley", "Everton", 1, 5), new Match("Crystal Palace", "Cardiff", 0, 0),
				new Match("Fulham", "Wolves", 1, 1), new Match("Leicester", "Man City", 2, 1),
				new Match("Liverpool", "Newcastle", 4, 0), new Match("Man United", "Huddersfield", 3, 1),
				new Match("Tottenham", "Bournemouth", 5, 0), new Match("Watford", "Chelsea", 1, 2),
				new Match("Southampton", "West Ham", 1, 2), new Match("Brighton", "Everton", 1, 0),
				new Match("Fulham", "Huddersfield", 1, 0), new Match("Leicester", "Cardiff", 0, 1),
				new Match("Liverpool", "Arsenal", 5, 1), new Match("Tottenham", "Wolves", 1, 3),
				new Match("Watford", "Newcastle", 1, 1), new Match("Burnley", "West Ham", 2, 0),
				new Match("Crystal Palace", "Chelsea", 0, 1), new Match("Man United", "Bournemouth", 4, 1),
				new Match("Southampton", "Man City", 1, 3), new Match("Arsenal", "Fulham", 4, 1),
				new Match("Cardiff", "Tottenham", 0, 3), new Match("Everton", "Leicester", 0, 1),
				new Match("Bournemouth", "Watford", 3, 3), new Match("Chelsea", "Southampton", 0, 0),
				new Match("Huddersfield", "Burnley", 1, 2), new Match("Newcastle", "Man United", 0, 2),
				new Match("West Ham", "Brighton", 2, 2), new Match("Wolves", "Crystal Palace", 0, 2),
				new Match("Man City", "Liverpool", 2, 1), new Match("Brighton", "Liverpool", 0, 1),
				new Match("Burnley", "Fulham", 2, 1), new Match("Cardiff", "Huddersfield", 0, 0),
				new Match("Chelsea", "Newcastle", 2, 1), new Match("Crystal Palace", "Watford", 1, 2),
				new Match("Leicester", "Southampton", 1, 2), new Match("West Ham", "Arsenal", 1, 0),
				new Match("Everton", "Bournemouth", 2, 0), new Match("Tottenham", "Man United", 0, 1),
				new Match("Man City", "Wolves", 3, 0), new Match("Arsenal", "Chelsea", 2, 0),
				new Match("Bournemouth", "West Ham", 2, 0), new Match("Liverpool", "Crystal Palace", 4, 3),
				new Match("Man United", "Brighton", 2, 1), new Match("Newcastle", "Cardiff", 3, 0),
				new Match("Southampton", "Everton", 2, 1), new Match("Watford", "Burnley", 0, 0),
				new Match("Wolves", "Leicester", 4, 3), new Match("Fulham", "Tottenham", 1, 2),
				new Match("Huddersfield", "Man City", 0, 3), new Match("Arsenal", "Cardiff", 2, 1),
				new Match("Fulham", "Brighton", 4, 2), new Match("Huddersfield", "Everton", 0, 1),
				new Match("Man United", "Burnley", 2, 2), new Match("Newcastle", "Man City", 2, 1),
				new Match("Wolves", "West Ham", 3, 0), new Match("Bournemouth", "Chelsea", 4, 0),
				new Match("Liverpool", "Leicester", 1, 1), new Match("Southampton", "Crystal Palace", 1, 1),
				new Match("Tottenham", "Watford", 2, 1), new Match("Brighton", "Watford", 0, 0),
				new Match("Burnley", "Southampton", 1, 1), new Match("Cardiff", "Bournemouth", 2, 0),
				new Match("Chelsea", "Huddersfield", 5, 0), new Match("Crystal Palace", "Fulham", 2, 0),
				new Match("Everton", "Wolves", 1, 3), new Match("Tottenham", "Newcastle", 1, 0),
				new Match("Leicester", "Man United", 0, 1), new Match("Man City", "Arsenal", 3, 1),
				new Match("West Ham", "Liverpool", 1, 1), new Match("Everton", "Man City", 0, 2),
				new Match("Brighton", "Burnley", 1, 3), new Match("Crystal Palace", "West Ham", 1, 1),
				new Match("Fulham", "Man United", 0, 3), new Match("Huddersfield", "Arsenal", 1, 2),
				new Match("Liverpool", "Bournemouth", 3, 0), new Match("Southampton", "Cardiff", 1, 2),
				new Match("Watford", "Everton", 1, 0), new Match("Man City", "Chelsea", 6, 0),
				new Match("Tottenham", "Leicester", 3, 1), new Match("Wolves", "Newcastle", 1, 1),
				new Match("Cardiff", "Watford", 1, 5), new Match("West Ham", "Fulham", 3, 1),
				new Match("Bournemouth", "Wolves", 1, 1), new Match("Burnley", "Tottenham", 2, 1),
				new Match("Leicester", "Crystal Palace", 1, 4), new Match("Newcastle", "Huddersfield", 2, 0),
				new Match("Arsenal", "Southampton", 2, 0), new Match("Man United", "Liverpool", 0, 0),
				new Match("Cardiff", "Everton", 0, 3), new Match("Huddersfield", "Wolves", 1, 0),
				new Match("Leicester", "Brighton", 2, 1), new Match("Newcastle", "Burnley", 2, 0),
				new Match("Arsenal", "Bournemouth", 5, 1), new Match("Chelsea", "Tottenham", 2, 0),
				new Match("Crystal Palace", "Man United", 1, 3), new Match("Liverpool", "Watford", 5, 0),
				new Match("Man City", "West Ham", 1, 0), new Match("Southampton", "Fulham", 2, 0),
				new Match("Bournemouth", "Man City", 0, 1), new Match("Brighton", "Huddersfield", 1, 0),
				new Match("Burnley", "Crystal Palace", 1, 3), new Match("Man United", "Southampton", 3, 2),
				new Match("Tottenham", "Arsenal", 1, 1), new Match("West Ham", "Newcastle", 2, 0),
				new Match("Wolves", "Cardiff", 2, 0), new Match("Everton", "Liverpool", 0, 0),
				new Match("Fulham", "Chelsea", 1, 2), new Match("Watford", "Leicester", 2, 1),
				new Match("Cardiff", "West Ham", 2, 0), new Match("Crystal Palace", "Brighton", 1, 2),
				new Match("Huddersfield", "Bournemouth", 0, 2), new Match("Leicester", "Fulham", 3, 1),
				new Match("Man City", "Watford", 3, 1), new Match("Newcastle", "Everton", 3, 2),
				new Match("Southampton", "Tottenham", 2, 1), new Match("Arsenal", "Man United", 2, 0),
				new Match("Chelsea", "Wolves", 1, 1), new Match("Liverpool", "Burnley", 4, 2),
				new Match("Bournemouth", "Newcastle", 2, 2), new Match("Burnley", "Leicester", 1, 2),
				new Match("West Ham", "Huddersfield", 4, 3), new Match("Everton", "Chelsea", 2, 0),
				new Match("Fulham", "Liverpool", 1, 2), new Match("Brighton", "Southampton", 0, 1),
				new Match("Burnley", "Wolves", 2, 0), new Match("Crystal Palace", "Huddersfield", 2, 0),
				new Match("Fulham", "Man City", 0, 2), new Match("Leicester", "Bournemouth", 2, 0),
				new Match("Man United", "Watford", 2, 1), new Match("West Ham", "Everton", 0, 2),
				new Match("Cardiff", "Chelsea", 1, 2), new Match("Liverpool", "Tottenham", 2, 1),
				new Match("Arsenal", "Newcastle", 2, 0), new Match("Watford", "Fulham", 4, 1),
				new Match("Wolves", "Man United", 2, 1), new Match("Chelsea", "Brighton", 3, 0),
				new Match("Man City", "Cardiff", 2, 0), new Match("Tottenham", "Crystal Palace", 2, 0),
				new Match("Southampton", "Liverpool", 1, 3), new Match("Bournemouth", "Burnley", 1, 3),
				new Match("Huddersfield", "Leicester", 1, 4), new Match("Newcastle", "Crystal Palace", 0, 1),
				new Match("Everton", "Arsenal", 1, 0), new Match("Chelsea", "West Ham", 2, 0),
				new Match("Leicester", "Newcastle", 0, 1), new Match("Brighton", "Bournemouth", 0, 5),
				new Match("Burnley", "Cardiff", 2, 0), new Match("Fulham", "Everton", 2, 0),
				new Match("Man United", "West Ham", 2, 1), new Match("Southampton", "Wolves", 3, 1),
				new Match("Tottenham", "Huddersfield", 4, 0), new Match("Crystal Palace", "Man City", 1, 3),
				new Match("Liverpool", "Chelsea", 2, 0), new Match("Watford", "Arsenal", 0, 1),
				new Match("Brighton", "Cardiff", 0, 2), new Match("Bournemouth", "Fulham", 0, 1),
				new Match("Huddersfield", "Watford", 1, 2), new Match("Man City", "Tottenham", 1, 0),
				new Match("Newcastle", "Southampton", 3, 1), new Match("West Ham", "Leicester", 2, 2),
				new Match("Wolves", "Brighton", 0, 0), new Match("Arsenal", "Crystal Palace", 2, 3),
				new Match("Cardiff", "Liverpool", 0, 2), new Match("Everton", "Man United", 4, 0),
				new Match("Chelsea", "Burnley", 2, 2), new Match("Tottenham", "Brighton", 1, 0),
				new Match("Watford", "Southampton", 1, 1), new Match("Man United", "Man City", 0, 2),
				new Match("Wolves", "Arsenal", 3, 1), new Match("Liverpool", "Huddersfield", 5, 0),
				new Match("Brighton", "Newcastle", 1, 1), new Match("Crystal Palace", "Everton", 0, 0),
				new Match("Fulham", "Cardiff", 1, 0), new Match("Southampton", "Bournemouth", 3, 3),
				new Match("Tottenham", "West Ham", 0, 1), new Match("Watford", "Wolves", 1, 2),
				new Match("Burnley", "Man City", 0, 1), new Match("Leicester", "Arsenal", 3, 0),
				new Match("Man United", "Chelsea", 1, 1), new Match("Everton", "Burnley", 2, 0),
				new Match("Bournemouth", "Tottenham", 1, 0), new Match("Cardiff", "Crystal Palace", 2, 3),
				new Match("Newcastle", "Liverpool", 2, 3), new Match("West Ham", "Southampton", 3, 0),
				new Match("Wolves", "Fulham", 1, 0), new Match("Arsenal", "Brighton", 1, 1),
				new Match("Chelsea", "Watford", 3, 0), new Match("Huddersfield", "Man United", 1, 1),
				new Match("Man City", "Leicester", 1, 0), new Match("Brighton", "Man City", 1, 4),
				new Match("Burnley", "Arsenal", 1, 3), new Match("Crystal Palace", "Bournemouth", 5, 3),
				new Match("Fulham", "Newcastle", 0, 4), new Match("Leicester", "Chelsea", 0, 0),
				new Match("Liverpool", "Wolves", 2, 0), new Match("Man United", "Cardiff", 0, 2),
				new Match("Southampton", "Huddersfield", 1, 1), new Match("Tottenham", "Everton", 2, 2),
				new Match("Watford", "West Ham", 1, 4));

		// match data for premier league 17-18
		List<Match> matches1718 = Arrays.asList(new Match("Arsenal", "Leicester", 4, 3),
				new Match("Brighton", "Man City", 0, 2), new Match("Chelsea", "Burnley", 2, 3),
				new Match("Crystal Palace", "Huddersfield", 0, 3), new Match("Everton", "Stoke", 1, 0),
				new Match("Southampton", "Swansea", 0, 0), new Match("Watford", "Liverpool", 3, 3),
				new Match("West Brom", "Bournemouth", 1, 0), new Match("Man United", "West Ham", 4, 0),
				new Match("Newcastle", "Tottenham", 0, 2), new Match("Bournemouth", "Watford", 0, 2),
				new Match("Burnley", "West Brom", 0, 1), new Match("Leicester", "Brighton", 2, 0),
				new Match("Liverpool", "Crystal Palace", 1, 0), new Match("Southampton", "West Ham", 3, 2),
				new Match("Stoke", "Arsenal", 1, 0), new Match("Swansea", "Man United", 0, 4),
				new Match("Huddersfield", "Newcastle", 1, 0), new Match("Tottenham", "Chelsea", 1, 2),
				new Match("Man City", "Everton", 1, 1), new Match("Bournemouth", "Man City", 1, 2),
				new Match("Crystal Palace", "Swansea", 0, 2), new Match("Huddersfield", "Southampton", 0, 0),
				new Match("Man United", "Leicester", 2, 0), new Match("Newcastle", "West Ham", 3, 0),
				new Match("Watford", "Brighton", 0, 0), new Match("Chelsea", "Everton", 2, 0),
				new Match("Liverpool", "Arsenal", 4, 0), new Match("Tottenham", "Burnley", 1, 1),
				new Match("West Brom", "Stoke", 1, 1), new Match("Arsenal", "Bournemouth", 3, 0),
				new Match("Brighton", "West Brom", 3, 1), new Match("Everton", "Tottenham", 0, 3),
				new Match("Leicester", "Chelsea", 1, 2), new Match("Man City", "Liverpool", 5, 0),
				new Match("Southampton", "Watford", 0, 2), new Match("Stoke", "Man United", 2, 2),
				new Match("Burnley", "Crystal Palace", 1, 0), new Match("Swansea", "Newcastle", 0, 1),
				new Match("West Ham", "Huddersfield", 2, 0), new Match("Bournemouth", "Brighton", 2, 1),
				new Match("Crystal Palace", "Southampton", 0, 1), new Match("Huddersfield", "Leicester", 1, 1),
				new Match("Liverpool", "Burnley", 1, 1), new Match("Newcastle", "Stoke", 2, 1),
				new Match("Tottenham", "Swansea", 0, 0), new Match("Watford", "Man City", 0, 6),
				new Match("West Brom", "West Ham", 0, 0), new Match("Chelsea", "Arsenal", 0, 0),
				new Match("Man United", "Everton", 4, 0), new Match("Burnley", "Huddersfield", 0, 0),
				new Match("Everton", "Bournemouth", 2, 1), new Match("Leicester", "Liverpool", 2, 3),
				new Match("Man City", "Crystal Palace", 5, 0), new Match("Southampton", "Man United", 0, 1),
				new Match("Stoke", "Chelsea", 0, 4), new Match("Swansea", "Watford", 1, 2),
				new Match("West Ham", "Tottenham", 2, 3), new Match("Brighton", "Newcastle", 1, 0),
				new Match("Arsenal", "West Brom", 2, 0), new Match("Bournemouth", "Leicester", 0, 0),
				new Match("Chelsea", "Man City", 0, 1), new Match("Huddersfield", "Tottenham", 0, 4),
				new Match("Man United", "Crystal Palace", 4, 0), new Match("Stoke", "Southampton", 2, 1),
				new Match("West Brom", "Watford", 2, 2), new Match("West Ham", "Swansea", 1, 0),
				new Match("Arsenal", "Brighton", 2, 0), new Match("Everton", "Burnley", 0, 1),
				new Match("Newcastle", "Liverpool", 1, 1), new Match("Burnley", "West Ham", 1, 1),
				new Match("Crystal Palace", "Chelsea", 2, 1), new Match("Liverpool", "Man United", 0, 0),
				new Match("Man City", "Stoke", 7, 2), new Match("Swansea", "Huddersfield", 2, 0),
				new Match("Tottenham", "Bournemouth", 1, 0), new Match("Watford", "Arsenal", 2, 1),
				new Match("Brighton", "Everton", 1, 1), new Match("Southampton", "Newcastle", 2, 2),
				new Match("Leicester", "West Brom", 1, 1), new Match("West Ham", "Brighton", 0, 3),
				new Match("Chelsea", "Watford", 4, 2), new Match("Huddersfield", "Man United", 2, 1),
				new Match("Man City", "Burnley", 3, 0), new Match("Newcastle", "Crystal Palace", 1, 0),
				new Match("Southampton", "West Brom", 1, 0), new Match("Stoke", "Bournemouth", 1, 2),
				new Match("Swansea", "Leicester", 1, 2), new Match("Everton", "Arsenal", 2, 5),
				new Match("Tottenham", "Liverpool", 4, 1), new Match("Arsenal", "Swansea", 2, 1),
				new Match("Bournemouth", "Chelsea", 0, 1), new Match("Crystal Palace", "West Ham", 2, 2),
				new Match("Liverpool", "Huddersfield", 3, 0), new Match("Man United", "Tottenham", 1, 0),
				new Match("Watford", "Stoke", 0, 1), new Match("West Brom", "Man City", 2, 3),
				new Match("Brighton", "Southampton", 1, 1), new Match("Leicester", "Everton", 2, 0),
				new Match("Burnley", "Newcastle", 1, 0), new Match("Huddersfield", "West Brom", 1, 0),
				new Match("Newcastle", "Bournemouth", 0, 1), new Match("Southampton", "Burnley", 0, 1),
				new Match("Stoke", "Leicester", 2, 2), new Match("Swansea", "Brighton", 0, 1),
				new Match("West Ham", "Liverpool", 1, 4), new Match("Chelsea", "Man United", 1, 0),
				new Match("Everton", "Watford", 3, 2), new Match("Man City", "Arsenal", 3, 1),
				new Match("Tottenham", "Crystal Palace", 1, 0), new Match("Arsenal", "Tottenham", 2, 0),
				new Match("Bournemouth", "Huddersfield", 4, 0), new Match("Burnley", "Swansea", 2, 0),
				new Match("Crystal Palace", "Everton", 2, 2), new Match("Leicester", "Man City", 0, 2),
				new Match("Liverpool", "Southampton", 3, 0), new Match("Man United", "Newcastle", 4, 1),
				new Match("West Brom", "Chelsea", 0, 4), new Match("Watford", "West Ham", 2, 0),
				new Match("Brighton", "Stoke", 2, 2), new Match("West Ham", "Leicester", 1, 1),
				new Match("Crystal Palace", "Stoke", 2, 1), new Match("Liverpool", "Chelsea", 1, 1),
				new Match("Man United", "Brighton", 1, 0), new Match("Newcastle", "Watford", 0, 3),
				new Match("Swansea", "Bournemouth", 0, 0), new Match("Tottenham", "West Brom", 1, 1),
				new Match("Burnley", "Arsenal", 0, 1), new Match("Huddersfield", "Man City", 1, 2),
				new Match("Southampton", "Everton", 4, 1), new Match("Brighton", "Crystal Palace", 0, 0),
				new Match("Leicester", "Tottenham", 2, 1), new Match("Watford", "Man United", 2, 4),
				new Match("West Brom", "Newcastle", 2, 2), new Match("Arsenal", "Huddersfield", 5, 0),
				new Match("Bournemouth", "Burnley", 1, 2), new Match("Chelsea", "Swansea", 1, 0),
				new Match("Everton", "West Ham", 4, 0), new Match("Man City", "Southampton", 2, 1),
				new Match("Stoke", "Liverpool", 0, 3), new Match("Arsenal", "Man United", 1, 3),
				new Match("Brighton", "Liverpool", 1, 5), new Match("Chelsea", "Newcastle", 3, 1),
				new Match("Everton", "Huddersfield", 2, 0), new Match("Leicester", "Burnley", 1, 0),
				new Match("Stoke", "Swansea", 2, 1), new Match("Watford", "Tottenham", 1, 1),
				new Match("West Brom", "Crystal Palace", 0, 0), new Match("Bournemouth", "Southampton", 1, 1),
				new Match("Man City", "West Ham", 2, 1), new Match("Burnley", "Watford", 1, 0),
				new Match("Crystal Palace", "Bournemouth", 2, 2), new Match("Huddersfield", "Brighton", 2, 0),
				new Match("Newcastle", "Leicester", 2, 3), new Match("Swansea", "West Brom", 1, 0),
				new Match("Tottenham", "Stoke", 5, 1), new Match("West Ham", "Chelsea", 1, 0),
				new Match("Liverpool", "Everton", 1, 1), new Match("Man United", "Man City", 1, 2),
				new Match("Southampton", "Arsenal", 1, 1), new Match("Burnley", "Stoke", 1, 0),
				new Match("Crystal Palace", "Watford", 2, 1), new Match("Huddersfield", "Chelsea", 1, 3),
				new Match("Liverpool", "West Brom", 0, 0), new Match("Man United", "Bournemouth", 1, 0),
				new Match("Newcastle", "Everton", 0, 1), new Match("Southampton", "Leicester", 1, 4),
				new Match("Swansea", "Man City", 0, 4), new Match("Tottenham", "Brighton", 2, 0),
				new Match("West Ham", "Arsenal", 0, 0), new Match("Arsenal", "Newcastle", 1, 0),
				new Match("Brighton", "Burnley", 0, 0), new Match("Chelsea", "Southampton", 1, 0),
				new Match("Leicester", "Crystal Palace", 0, 3), new Match("Man City", "Tottenham", 4, 1),
				new Match("Stoke", "West Ham", 0, 3), new Match("Watford", "Huddersfield", 1, 4),
				new Match("Bournemouth", "Liverpool", 0, 4), new Match("West Brom", "Man United", 1, 2),
				new Match("Everton", "Swansea", 3, 1), new Match("Arsenal", "Liverpool", 3, 3),
				new Match("Brighton", "Watford", 1, 0), new Match("Burnley", "Tottenham", 0, 3),
				new Match("Everton", "Chelsea", 0, 0), new Match("Leicester", "Man United", 2, 2),
				new Match("Man City", "Bournemouth", 4, 0), new Match("Southampton", "Huddersfield", 1, 1),
				new Match("Stoke", "West Brom", 3, 1), new Match("Swansea", "Crystal Palace", 1, 1),
				new Match("West Ham", "Newcastle", 2, 3), new Match("Bournemouth", "West Ham", 3, 3),
				new Match("Chelsea", "Brighton", 2, 0), new Match("Huddersfield", "Stoke", 1, 1),
				new Match("Liverpool", "Swansea", 5, 0), new Match("Man United", "Burnley", 2, 2),
				new Match("Tottenham", "Southampton", 5, 2), new Match("Watford", "Leicester", 2, 1),
				new Match("West Brom", "Everton", 0, 0), new Match("Newcastle", "Man City", 0, 1),
				new Match("Crystal Palace", "Arsenal", 2, 3), new Match("Bournemouth", "Everton", 2, 1),
				new Match("Chelsea", "Stoke", 5, 0), new Match("Huddersfield", "Burnley", 0, 0),
				new Match("Liverpool", "Leicester", 2, 1), new Match("Man United", "Southampton", 0, 0),
				new Match("Newcastle", "Brighton", 0, 0), new Match("Watford", "Swansea", 1, 2),
				new Match("Crystal Palace", "Man City", 0, 0), new Match("West Brom", "Arsenal", 1, 1),
				new Match("Brighton", "Bournemouth", 2, 2), new Match("Burnley", "Liverpool", 1, 2),
				new Match("Everton", "Man United", 0, 2), new Match("Leicester", "Huddersfield", 3, 0),
				new Match("Stoke", "Newcastle", 0, 1), new Match("Man City", "Watford", 3, 1),
				new Match("Southampton", "Crystal Palace", 1, 2), new Match("Swansea", "Tottenham", 0, 2),
				new Match("West Ham", "West Brom", 2, 1), new Match("Arsenal", "Chelsea", 2, 2),
				new Match("Tottenham", "West Ham", 1, 1), new Match("Chelsea", "Leicester", 0, 0),
				new Match("Crystal Palace", "Burnley", 1, 0), new Match("Huddersfield", "West Ham", 1, 4),
				new Match("Newcastle", "Swansea", 1, 1), new Match("Tottenham", "Everton", 4, 0),
				new Match("Watford", "Southampton", 2, 2), new Match("West Brom", "Brighton", 2, 0),
				new Match("Bournemouth", "Arsenal", 2, 1), new Match("Liverpool", "Man City", 4, 3),
				new Match("Man United", "Stoke", 3, 0), new Match("Arsenal", "Crystal Palace", 4, 1),
				new Match("Brighton", "Chelsea", 0, 4), new Match("Burnley", "Man United", 0, 1),
				new Match("Everton", "West Brom", 1, 1), new Match("Leicester", "Watford", 2, 0),
				new Match("Man City", "Newcastle", 3, 1), new Match("Stoke", "Huddersfield", 2, 0),
				new Match("West Ham", "Bournemouth", 1, 1), new Match("Southampton", "Tottenham", 1, 1),
				new Match("Swansea", "Liverpool", 1, 0), new Match("Huddersfield", "Liverpool", 0, 3),
				new Match("Swansea", "Arsenal", 3, 1), new Match("West Ham", "Crystal Palace", 1, 1),
				new Match("Chelsea", "Bournemouth", 0, 3), new Match("Everton", "Leicester", 2, 1),
				new Match("Man City", "West Brom", 3, 0), new Match("Newcastle", "Burnley", 1, 1),
				new Match("Southampton", "Brighton", 1, 1), new Match("Stoke", "Watford", 0, 0),
				new Match("Tottenham", "Man United", 2, 0), new Match("Arsenal", "Everton", 5, 1),
				new Match("Bournemouth", "Stoke", 2, 1), new Match("Brighton", "West Ham", 3, 1),
				new Match("Burnley", "Man City", 1, 1), new Match("Leicester", "Swansea", 1, 1),
				new Match("Man United", "Huddersfield", 2, 0), new Match("West Brom", "Southampton", 2, 3),
				new Match("Crystal Palace", "Newcastle", 1, 1), new Match("Liverpool", "Tottenham", 2, 2),
				new Match("Watford", "Chelsea", 4, 1), new Match("Everton", "Crystal Palace", 3, 1),
				new Match("Man City", "Leicester", 5, 1), new Match("Stoke", "Brighton", 1, 1),
				new Match("Swansea", "Burnley", 1, 0), new Match("Tottenham", "Arsenal", 1, 0),
				new Match("West Ham", "Watford", 2, 0), new Match("Huddersfield", "Bournemouth", 4, 1),
				new Match("Newcastle", "Man United", 1, 0), new Match("Southampton", "Liverpool", 0, 2),
				new Match("Chelsea", "West Brom", 3, 0), new Match("Bournemouth", "Newcastle", 2, 2),
				new Match("Brighton", "Swansea", 4, 1), new Match("Burnley", "Southampton", 1, 1),
				new Match("Leicester", "Stoke", 1, 1), new Match("Liverpool", "West Ham", 4, 1),
				new Match("Watford", "Everton", 1, 0), new Match("West Brom", "Huddersfield", 1, 2),
				new Match("Crystal Palace", "Tottenham", 0, 1), new Match("Man United", "Chelsea", 2, 1),
				new Match("Arsenal", "Man City", 0, 3), new Match("Burnley", "Everton", 2, 1),
				new Match("Leicester", "Bournemouth", 1, 1), new Match("Liverpool", "Newcastle", 2, 0),
				new Match("Southampton", "Stoke", 0, 0), new Match("Swansea", "West Ham", 4, 1),
				new Match("Tottenham", "Huddersfield", 2, 0), new Match("Watford", "West Brom", 1, 0),
				new Match("Brighton", "Arsenal", 2, 1), new Match("Man City", "Chelsea", 1, 0),
				new Match("Crystal Palace", "Man United", 2, 3), new Match("Chelsea", "Crystal Palace", 2, 1),
				new Match("Everton", "Brighton", 2, 0), new Match("Huddersfield", "Swansea", 0, 0),
				new Match("Man United", "Liverpool", 2, 1), new Match("Newcastle", "Southampton", 3, 0),
				new Match("West Brom", "Leicester", 1, 4), new Match("West Ham", "Burnley", 0, 3),
				new Match("Arsenal", "Watford", 3, 0), new Match("Bournemouth", "Tottenham", 1, 4),
				new Match("Stoke", "Man City", 0, 2), new Match("Bournemouth", "West Brom", 2, 1),
				new Match("Huddersfield", "Crystal Palace", 0, 2), new Match("Liverpool", "Watford", 5, 0),
				new Match("Stoke", "Everton", 1, 2), new Match("Brighton", "Leicester", 0, 2),
				new Match("Crystal Palace", "Liverpool", 1, 2), new Match("Everton", "Man City", 1, 3),
				new Match("Man United", "Swansea", 2, 0), new Match("Newcastle", "Huddersfield", 1, 0),
				new Match("Watford", "Bournemouth", 2, 2), new Match("West Brom", "Burnley", 1, 2),
				new Match("West Ham", "Southampton", 3, 0), new Match("Arsenal", "Stoke", 3, 0),
				new Match("Chelsea", "Tottenham", 1, 3), new Match("Bournemouth", "Crystal Palace", 2, 2),
				new Match("Brighton", "Huddersfield", 1, 1), new Match("Everton", "Liverpool", 0, 0),
				new Match("Leicester", "Newcastle", 1, 2), new Match("Man City", "Man United", 2, 3),
				new Match("Stoke", "Tottenham", 1, 2), new Match("Watford", "Burnley", 1, 2),
				new Match("West Brom", "Swansea", 1, 1), new Match("Arsenal", "Southampton", 3, 2),
				new Match("Chelsea", "West Ham", 1, 1), new Match("Burnley", "Leicester", 2, 1),
				new Match("Crystal Palace", "Brighton", 3, 2), new Match("Huddersfield", "Watford", 1, 0),
				new Match("Liverpool", "Bournemouth", 3, 0), new Match("Southampton", "Chelsea", 2, 3),
				new Match("Swansea", "Everton", 1, 1), new Match("Tottenham", "Man City", 1, 3),
				new Match("Man United", "West Brom", 0, 1), new Match("Newcastle", "Arsenal", 2, 1),
				new Match("West Ham", "Stoke", 1, 1), new Match("Brighton", "Tottenham", 1, 1),
				new Match("Bournemouth", "Man United", 0, 2), new Match("Burnley", "Chelsea", 1, 2),
				new Match("Leicester", "Southampton", 0, 0), new Match("Watford", "Crystal Palace", 0, 0),
				new Match("West Brom", "Liverpool", 2, 2), new Match("Arsenal", "West Ham", 4, 1),
				new Match("Man City", "Swansea", 5, 0), new Match("Stoke", "Burnley", 1, 1),
				new Match("Everton", "Newcastle", 1, 0), new Match("Burnley", "Brighton", 0, 0),
				new Match("Crystal Palace", "Leicester", 5, 0), new Match("Huddersfield", "Everton", 0, 2),
				new Match("Liverpool", "Stoke", 0, 0), new Match("Newcastle", "West Brom", 0, 1),
				new Match("Southampton", "Bournemouth", 2, 1), new Match("Swansea", "Chelsea", 0, 1),
				new Match("Man United", "Arsenal", 2, 1), new Match("West Ham", "Man City", 1, 4),
				new Match("Tottenham", "Watford", 2, 0), new Match("Brighton", "Man United", 1, 0),
				new Match("Bournemouth", "Swansea", 1, 0), new Match("Everton", "Southampton", 1, 1),
				new Match("Leicester", "West Ham", 0, 2), new Match("Stoke", "Crystal Palace", 1, 2),
				new Match("Watford", "Newcastle", 2, 1), new Match("West Brom", "Tottenham", 1, 0),
				new Match("Arsenal", "Burnley", 5, 0), new Match("Chelsea", "Liverpool", 1, 0),
				new Match("Man City", "Huddersfield", 0, 0), new Match("Swansea", "Southampton", 0, 1),
				new Match("Chelsea", "Huddersfield", 1, 1), new Match("Leicester", "Arsenal", 3, 1),
				new Match("Man City", "Brighton", 3, 1), new Match("Tottenham", "Newcastle", 1, 0),
				new Match("West Ham", "Man United", 0, 0), new Match("Burnley", "Bournemouth", 1, 2),
				new Match("Crystal Palace", "West Brom", 2, 0), new Match("Huddersfield", "Arsenal", 0, 1),
				new Match("Liverpool", "Brighton", 4, 0), new Match("Man United", "Watford", 1, 0),
				new Match("Newcastle", "Chelsea", 3, 0), new Match("Southampton", "Man City", 0, 1),
				new Match("Swansea", "Stoke", 1, 2), new Match("Tottenham", "Leicester", 5, 4),
				new Match("West Ham", "Everton", 3, 1));

		LeagueTable table = new LeagueTable(matches1920);
		List<LeagueTableEntry> list = table.getTableEntries();
		System.out.println("Premier League 2019-2020");
		printTableResultOnConsole(list);
		
		System.out.println("\nPremier League 2018-2019");
		table = new LeagueTable(matches1819);
		list = table.getTableEntries();
		printTableResultOnConsole(list);

		System.out.println("\nPremier League 2017-2018");
		table = new LeagueTable(matches1718);
		list = table.getTableEntries();
		printTableResultOnConsole(list);
		
	}
	
	  private static void printTableResultOnConsole(List<LeagueTableEntry> tableEntries)
	  {	
			System.out.printf("%-4s %-25s %5s %5s %5s %5s %5s %5s %5s %5s\n", "#", "Team", "Pl", "W", "D", "L", "F",
					"A", "GD", "Pts");
	    for (int i = 0; i < tableEntries.size(); i++)
	    {
	      LeagueTableEntry tableEntry = tableEntries.get(i);
	      System.out.printf("%-4d %-25s %5d %5d %5d %5d %5d %5d %+5d %5d\n",
	          (i + 1),
	          tableEntry.getTeamName(),
	          tableEntry.getPlayed(),
	          tableEntry.getWon(),
	          tableEntry.getDrawn(),
	          tableEntry.getLost(),
	          tableEntry.getGoalsFor(),
	          tableEntry.getGoalsAgainst(),
	          tableEntry.getGoalDifference(),
	          tableEntry.getPoints());
	    }
	  }	  
}
